//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisWebProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bolum
    {
        public int BolumId { get; set; }
        public string BolumAd { get; set; }
    
        public virtual DısHekimi DısHekimi { get; set; }
    }
}
