//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisWebProje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Randevu
    {
        public string HastaAdi { get; set; }
        public string HastaTc { get; set; }
        public string DoktorAdi { get; set; }
        public string Islem { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
    
        public virtual Hasta Hasta { get; set; }
    }
}
