//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisWebProje.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Islemler
    {
        public int IslemId { get; set; }
        public string IslemAdı { get; set; }
        public string IslemUcret { get; set; }
    }
}
