//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DisWebProje.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class denemeEntities2 : DbContext
    {
        public denemeEntities2()
            : base("name=denemeEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bolum> Bolum { get; set; }
        public virtual DbSet<DısHekimi> DısHekimi { get; set; }
        public virtual DbSet<Hasta> Hasta { get; set; }
        public virtual DbSet<Islemler> Islemler { get; set; }
        public virtual DbSet<Randevu> Randevu { get; set; }
    }
}
